### ISSUE TITLE
Code coverage for mocha-expect branch

### ISSUE THREAD

**Issue by lostm1nd** [LittleFurryBastards/webpack-react-redux#3]
Try to implement code coverage for source files.

Currently I had no luck with configuring istanbul for coverage.

**Comment by Chariyski** [comment]
check if that can help https://github.com/SAP/ui5-inspector/blob/master/karma.conf.js

**Comment by lostm1nd** [comment]
That config is for karma, I am using just mocha and expect ; )

**Comment by Chariyski** [comment]
my bad :D :angel:

**Comment by lostm1nd** [comment]
Real pain to cover react + es2015 + etc.

https://github.com/gotwarlost/istanbul/issues/496
https://github.com/JakeSidSmith/istanbul-no-coverage/pull/1
https://drublic.de/blog/es6-modules-using-browserify-mocha/

**Comment by Chariyski** [comment]
xaxaxax :D

**Comment by aleksandrenko** [comment]
No test, no problem 😺
